name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  token:
    description: The GitHub API token to use for creating PR reviews
    required: true
  failIf:
    description: Fail if *any* violations are detected or only *new* ones (valid values are "new" or "any")
    required: false
    default: new
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/goodbye.sh
      shell: bash
    - run: sudo apt-get install python3-setuptools
      shell: bash
    - run: python3 -m venv .venv
      shell: bash
    - run: source .venv/bin/activate && pip3 install bandit ttam-lintly
      shell: bash
    - run: source .venv/bin/activate && bandit -r . --format=json --exclude=./.venv/| lintly --api-key ${{ inputs.token }} --fail-on ${{ inputs.failIf }} --log --no-post-status --format=bandit-json
      shell: bash